FROM node:alpine

WORKDIR '/app'

# Copy package.json first to avoid unnecessary npm installs
COPY package.json .
RUN npm install

# Copy everything else
COPY . .

# Default command
CMD ["npm", "run", "start"]